@startuml DiagramaPaquetes

[ControladorPrincipal]

package enums {
    [tipoSesion]
    [TipoArticulo]
}

package gestion{

    package gestionConferencias {
        [Conferencia]
        [Sesion]
        [Singleton]
    }

    package gestionUsuarios {
        [Usuario]
        [FactoryUsuario]
        [Rol]
        [Autor]
        [Revisor]
        [Chair]
    }

    package gestionArticulos {
        [Articulo]
        [ArticuloRegular]
        [ArticuloPoster]
        [FactoryArticulo]
        [Revision]
        [Observer]
    }
}

package procesos {
    [ProcesoRecepcion]
    [ProcesoBidding]
    [ProcesoRevision]
    [ProcesoSeleccion]
}

package criteriosSeleccion {
    [CriterioSeleccion]
    [CorteFijo]
    [Mejores]
    [Strategy]
}

package servicios {
    [ServicioConferencia]
    [ServicioUsuario]
    [ServicioSesion]
    [ServicioArticulo]
}


ControladorPrincipal -down--> servicios : gestiona
 servicios -down--> gestion : crea/edita/registra/autentica
 gestion -left--> procesos : aplica
 gestion --> enums : utiliza
 procesos --> criteriosSeleccion : aplica

@enduml